[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0e82663cb827e48cf24577477f7a18519c2faa6"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "700d820ae5a938c94061990cd3ce75ef4836a4b269465aa4f24ee9e649c7fdc6"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b11a5b295bea8b8b6b4aac587ee0a7dac63be893"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "07a466a0796616ee5372440df1c8f56984b097069d9e40ab21bd7baa9dd5ef4a"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c19ebde0dbbe37ad8c42f186eec5bdb3b7476a65"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "51a3c50e0dbe41336a44cae6ddf1b81d00aa6b36fe88319bcb8eab61533b38aa"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "361995a6a30d5bade01db883c879c9377bf1e90b"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "ff66a8378c4bc14c5226f40f3b9f97363f94ca561c5e8e9c949c949b6306d7e7"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b1900d8424f21bdcbd5070d8ccba73a7e647cb3"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "5ac7b50fa3e90cefe43cdfcd69459725de65fefaf2b5851649093dcffeab9a13"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee5e3985cfe7e8dff871eb91c15f17b5927f1bbf"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "39c8755ebd5afebbfe6aff04bba2c426d17a2ace859d632607f55f5807d56434"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61b89655df2a6e592f864803b33fdba2ebd3cad1"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "8cad96631a6b42628ed819485566afd4c63fda80d1c8ea588b928a42f21ded84"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "308373b005ce12005064528a0bd3646c173a10dd"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "71cc030593d31e2497c0e26069f192660e017f4995f1677fd11d50bf48dc340a"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "659a41616ec96aae398c641a14250b35a86888fb"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "88c85fc00fa601fc16ab9ccff84e23c07b3f93c7745beba20de0215fc3b79b57"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.i686-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd6729151b1988b4ac72d9fa975f8658e86f297d"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "a54dd76645f9ae2d18d6b2f3256ff11c1a93959c07204de9f8c4e3db05317c8e"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.i686-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71a3027ebbd9c9ce7c1b5ace2e6f6d84303e0ec2"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "f39866108c29830a5ab5b22ce8d6f5478241c5c8dbf1bee99b32294a707a22c4"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.i686-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c6aad6ce2c4a07cdeb9a54fcf894ad725a09aed"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "e8259bf61f4002b85cd826d608699619f5e47ff72e80d8f787d9994486314d1a"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.i686-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ff1062bae11011ee5e0fef1e498a8c435310c89"
os = "windows"

    [[SHOT.download]]
    sha256 = "b2eb30437ff30a4db00bfa6a3ae0959b99f41846f9220c83fd90c48cb74551b8"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc0b0038e470123309ac0ef9f1c147b89f4c15bb"
os = "windows"

    [[SHOT.download]]
    sha256 = "045b97ebfac02a704b3919315491d33bfc435591128232acbcff9c04515f67ff"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[SHOT]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "109480dbf66208b0a14dce00759f3d402d7c147d"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "2e85dfb1612b779996d8e7f7ec2e7d7a82d4eaa5830299fd59838ff88033e9ae"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a8122d9b83aecf634b0ed2ea24a01f1bae24e58"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "a3ab2d5ed1c6dd979f07b949090df7087fafb937e86bcb124ef1c429a80796da"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
git-tree-sha1 = "ba28f802a877e8af0827b2e084f1f7a8cef590c1"
os = "macos"

    [[SHOT.download]]
    sha256 = "42ba4d339a939e2edef50b0cbdf409a0ae8982197021732fbc02d3cb09e703c5"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-apple-darwin.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f40ed0703c83d262b03ce66c0994b1b2cb11a50a"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "8bdb6c72a3494091d40e0a77781fbe0c085f836efc22534f21e906f0206f3c0a"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13279f11f72f7832bf5bd0be0e342b5c912b841c"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "baf16f45653350ac63dd7457746b57ab1ddd500d9d1b5a22f42bf3249f971f34"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bba13a6105067fc91d016f4bd6c16d52da006113"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "941127ea1c1dc3c94fd87aa0148b5fa4763469d9c5896abd4c252bd30d7e4995"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c17f15b47ca37d098cadd6b56694d59ab242a1e"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "6d95b2ee1c08e067ebb6c6c88f7a18bb86df02682d0f38b94c8094ab8e431b4a"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbd8939b72dcdaed7fb091b5fda2dc29acded797"
os = "windows"

    [[SHOT.download]]
    sha256 = "60dfaeccc3059bc4dac034eec170d26c67f7b07a24e54a1aec5a0dd32241a127"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66e8577e313e50ad3c5fb0b9e67f598427295982"
os = "windows"

    [[SHOT.download]]
    sha256 = "c68d43c1e28665dc6c2bba049d90d8a843bd2021ff5a97b532abe5dc4e1b9471"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+2/SHOT.v1.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
