[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ab0839daf1e8ae98e986c89dfa03675bacd6057"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "591b6a96a78fc444d13e9bef29b397885f6aafae094ca7b9cbc15241dacef090"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9f2c6fa2050b612b8e5a962220a9820cf04d67c"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "3dd4e76c35b05f569d1ce955e464abcd1a7ed0714fcc5a2eaab76ea1e0ee929c"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2c64e5906e158c5c5f1ade7114763cc6317376f"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "21191730bb685b6ced2fd5c54acdaea19b0ed9def3c9d09eecbb8c493127ddfc"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0601a766a9a8bc23e35fc6abe1e864360d7bcf99"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "9faa81ad59f2cb1a66de9c964d49ba3d6805a56745ee3c19aa82482185de2469"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eef44f85748787820b589b9f8634ac7a8bc8c97"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "c52402b828d77c934512df90df8547d092f4620e6b82ecd3650ae86c31db9bd7"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1cb95411e5f92cbc5bf6821dd39388f0c168176"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "0733677cf15dd4d543bb4c95e139d5ee18d31bfe968a10e8388c1833ddafb82d"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e615e1f7bd3d7afde277a865564e12a58ffb33fc"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "593dddbede1d4466b7f8ef1d0280c28ec9a211dd555f12d545517d808d2083dc"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af4df1a388339408db6f3ea70ff63a6da0bbb7e2"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "fac04abc3a79b02ac05a0a04740d78a45d1da6e2b69e901942ca7c3d7c3a8677"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3b50e73656bfd51b675f50dbd62f8db147e71d1"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "4f8722ad6542071ceeeeea6406603cf8f6601f9ee896fd129e0a40857e614e45"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.i686-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38bae20e08b93a5607544aba7322577b9a3abc28"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "35da2de60e3e0402576db41ae5a514ec293acd44143938fcbcaed36e18b5c8c0"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.i686-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b21b45a5cd705cd8cad2654c95dc694e354f1bc0"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "ca012419c474810b63db8e01490a292b248889513652dd34e366abb439aa7d5d"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.i686-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5d0ccd433ad134081b103943e5cc1a4a274404a"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "09215bd9b405ec35833e9d3c683f432e37ea74eee99a897a04565038c5ca9550"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.i686-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a52ef7ef0f690a5d19a78337cc2d75d261856f5c"
os = "windows"

    [[SHOT.download]]
    sha256 = "2bcbd28908f1ae1a82dbf4abf6dbb9ab48496663f73f63b4b23e8511dca87320"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "129468765f06d14badef2258ab3d44f53222efa5"
os = "windows"

    [[SHOT.download]]
    sha256 = "5cf7af511fed0747901516e56ff4bf94b60f0f6022599740edb2fb24573e4503"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[SHOT]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfb62a0c855380e665eff8adf3a1c83df37c3f29"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "c7a3f8dd4b5ef7e3e53da349c5037d4a9f131c0d1c5adfa32ec296e4525c714f"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12189c4f32c2344a9a7a5878e1b2c741b29ddb36"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "99bdde94c9b5e5758e8bc1e1cc15c13993277ed3fcc5b6efdb2b6431c3fa287c"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
git-tree-sha1 = "96ea9cafa7fd20d46f515e8c8efdc658b91d48f3"
os = "macos"

    [[SHOT.download]]
    sha256 = "6cb33ef767dd1b1b397e782e7b8045d3b4a6b0789eb2341c8f1c9e323e34a840"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-apple-darwin.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edeb6ad3f2be3311b16d979c44aa993dcd704edf"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "764fbba54312ad60a88db1e3eb1802078b77425cca13bb32184cc2b24dccf95e"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33b037f29d9565fc31ac91a4892aba10d845c8cb"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "32a14fc6e34ef6f695d6738f6c0f1eb60522284daef407d98028bf1507e29bcf"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e64d648a1982ee9b9ce55e385f34c50fbabc2d3"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "3b7de2e7b008e71cad08c1b61e305dbd44c3bd880b0a999c4adaf82075ffba5e"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ccb37cc393c8fce1690826de103a90033c6ad30"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "5e4103424a957956884847c619ede1490cb7b725455bf8d946b6cca594c32489"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7b4e76b6ba9a73735eac3f392342b1bedea65c1"
os = "windows"

    [[SHOT.download]]
    sha256 = "f7b1c60e2c9f4fb1258cb8f1b6c31397a9eb28c0a16e0f0388695e7311a11968"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b53fb62096f1d9ccdba34a34c55eaa79b587d9de"
os = "windows"

    [[SHOT.download]]
    sha256 = "e3b5fda7768915dbb684a1ae7938f357e911a05ec94fee3394865a384d3d8a3c"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v1.0.1+1/SHOT.v1.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
