[[SHOT]]
arch = "aarch64"
git-tree-sha1 = "c18d53d4006072089c06e71f868037142990bf4a"
os = "macos"

    [[SHOT.download]]
    sha256 = "fd6fb3a479ace68b90ec4f8a979ef23df7dcbfaf4ddd9ce5c510e5e07be60897"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.aarch64-apple-darwin.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7be7b4c151b6acf8bfa73186be84c7856209b371"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "55d085dcf412d5f4285223a9c8292850569de917e944499cab3072cbd857b690"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3bf7895172409ca6d93ca637a7ffd3c56ced306"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "01b0982add17661b42640dcb5a2cc81f019f2bb99919c90cef40420686204b69"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c77e6b66fbdcbbb03e6a5580d20cf3e6ad922d9"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "2b0272fd0521faa399f6bf065a445818739c17f16fa9fcbcd2ae7fcbdc4d43b6"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.aarch64-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d9b69c310a892ae03c18e3ccb2747bd356e74da"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "71cae65bcd1ebcfb4a182c18e525f166b0212f86d7685134f428317ee7c314d1"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.aarch64-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d861df49aed4d28640e4af9b23dfa137c0edf01"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "7c336f443bd989df0507bd9fb1d45ad9664ba975dd2985ebf0d7e4310d1d6908"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "564c50cc13b6ea287396966b86408d7a992e0225"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "b9a83422ceaa0a142f4aeef40abee8b0b3071af1f240d1f746151fb070c4caff"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SHOT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29f384249e64a466d4aa8d9c967b07aa8f8debf1"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "cb31f8028487899dc58ecaad99a9c49e44dabf4b0bdd6e8f3947a7d29424a8e3"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccf9abf59de3d0a4c963f865734b0f102861bda7"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "7d99a36771c643dfea0880ec8dd517a898ee46836eb34f372f348b8d5c7036b5"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad83ebe2b362ea7054d0965711869c45858ed197"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "c765dffa0c972cbf3b0e6ce9a06952ef75ced172db1e57ecc36e036b9f2c5f89"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "271b288e881e686cc3977d281d3c3fd553216ff4"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "d2f16d20b8e2a2d8e93fc8f5400aa89fb8b921ba3d1cf71a942e6e3fd62accdc"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13aed88ed3ce3c1c50c81386526412cd76918d81"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "38a3ff806da10766b6a25aa0c7b2b0bfbbbc8e1ecb3843e77db9617d27f2119f"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SHOT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "755c36575b07542038cb3eaabb5eddd179c23e58"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "e10b216220fdeebdd2ac4513c149b4fa511f93ae35dab6c5688f87fca85cfda3"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20b62ad6e6387b263ac4f65fe9c794356250f82d"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "8cf2f67ef5fb96440ac729b13a3e15dd91c2cc1a3cd0470804eec4528909eb7d"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.i686-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee2109f7da50b6cc35d95b2ba39b5fea490d7582"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "fbcf0d1c496f515973155aeb024d033a208aeb1da1a01544b9d7cc73fce6b14d"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.i686-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f1044de87709451b128923812f87e45407f5909"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "c1e442a56ba3dc4b343ee564e9b15c0bc2d60b41aaea93563eb534d50f72355f"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.i686-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97f7c509dd286a6c16057f3db268e49c2c444357"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "a156bd781c6f1effe9d5de43d0f2800a9fe11bc8ecf9571c61c45a339bc28740"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.i686-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9133b19fd301f96cc3df7c3caddc38989d8d1fc5"
os = "windows"

    [[SHOT.download]]
    sha256 = "827de62dbb25c97350f09eba907fe25a675b5d4bbddbe408f485491052fe09f8"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.i686-w64-mingw32-cxx03.tar.gz"
[[SHOT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c304018056aeae5630bd2cb6416a2a99439516fd"
os = "windows"

    [[SHOT.download]]
    sha256 = "cc09052aecb3afbe216d0437a95f29ed62414a3d870b5a9dcb8d56f392f5f107"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.i686-w64-mingw32-cxx11.tar.gz"
[[SHOT]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90d06676d958b5a91b3c30afe0e79140e4597723"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "56c297b7dbfb8d0f059abb0cac431640f718005112da1951a3eacce495252d1f"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b8bc80a32ee3a53721d9b8ac3b0a8813a8fdf0c"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "928fcdab6619a9b0717e7717ff8710f7bbc7c4a7e4130432444c8b814f0b8d1d"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
git-tree-sha1 = "b3d4c19a17189666169301fa4cdf47b2ec637da8"
os = "macos"

    [[SHOT.download]]
    sha256 = "ddd03993c9e97e40373f3f02c29b86e75c1540a2852a9d39151ceb9355fafbee"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-apple-darwin.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11217eff6098683941745d75d28c796b51099060"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "176cdb2257c7cd29b68e8bc0b51bdb44a3176948dc4ddbf15949133734fa26dc"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5dab77e5dcd2b0729e5de6f648b919c15991337"
libc = "glibc"
os = "linux"

    [[SHOT.download]]
    sha256 = "9692b722ca094da2dfac01b93599513ce175e96a55a6e0a0ad11c5eb84377c81"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cd0ab65fa0e4cb9247f92af17d7f0be5fac55b5"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "2ece578dce21c57dd3e9b7e4eb51127288817b2c8970d601e77e603b8b4d87a9"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-linux-musl-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7d5ae576ff0409b958b2379a762df5163460d48"
libc = "musl"
os = "linux"

    [[SHOT.download]]
    sha256 = "fd4d4a5a1a286f1b74a4ca5337e5c7b7ce3e80218131f981d091e0f56820e502"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-linux-musl-cxx11.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d16385489e17c5171537f57ff7194d63161f2d51"
os = "windows"

    [[SHOT.download]]
    sha256 = "12a41fcfbc116e38c8fa030641a0ad0914759f792a8528eb57aa29acd5c59712"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SHOT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0005023f67d8548da6c2bc7eb0dc7737aefbaa6"
os = "windows"

    [[SHOT.download]]
    sha256 = "5036a635bfe02ae330764b1102059ad29a99a3d3148cf52311b2046c18ea6be8"
    url = "https://github.com/JuliaBinaryWrappers/SHOT_jll.jl/releases/download/SHOT-v100.100.0+0/SHOT.v100.100.0.x86_64-w64-mingw32-cxx11.tar.gz"
